[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
chrono = "0.4.19"
futures = "0.3.17"
hyper = { version = "0.14.14", features = ["full"] }
reqwest = { version = "0.11.6", features = ["blocking"] }
rocket = "0.4.10"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.69"
tokio = { version = "1.13.0", features = ["full"] }