[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2021"

[dependencies]
actix = "0.13.3"
actix-rt = "2.9.0"
actix-web = "4.6.0"
anyhow = "1.0.86"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
chrono = "0.4.38"
futures = "0.3.30"
hyper = { version = "0.14.28", features = ["full"] }
log = "0.4.21"
log4rs = "1.3.0"
reqwest = { version = "0.11.27", features = ["blocking"] }
rocket = "0.5.0"
rusqlite = "0.29.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
sqlx = { version = "0.7.2", features = [ "runtime-tokio", "tls-native-tls" , "postgres" ] }
tide = "0.16.0"
tokio = { version = "1.37.0", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3