[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2021"

[dependencies]
actix = "0.12.0"
actix-rt = "2.7.0"
actix-web = "3.3.3"
anyhow = "1.0.57"
chrono = "0.4.19"
futures = "0.3.21"
hyper = { version = "0.14.18", features = ["full"] }
tide = "0.16.0"
async-std = { version = "1.11.0", features = ["attributes", "tokio1"] }
reqwest = { version = "0.11.10", features = ["blocking"] }
rocket = "0.5.0-rc.1"
rusqlite = "0.26.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
sqlx = { version = "0.5.13", features = [ "runtime-actix-native-tls" , "postgres" ] }
tokio = { version = "1.17.0", features = ["full"] }
log = "0.4.16"
log4rs = "1.1.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3