[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2021"

[dependencies]
actix-web = "3"
anyhow = "1.0.48"
chrono = "0.4.19"
futures = "0.3.17"
hyper = { version = "0.14.14", features = ["full"] }
tide = "0.16.0"
async-std = { version = "1.10.0", features = ["attributes", "tokio1"] }
reqwest = { version = "0.11.6", features = ["blocking"] }
rocket = "0.5.0-rc.1"
rusqlite = "0.26.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
sqlx = { version = "0.5.9", features = [ "runtime-actix-native-tls" , "postgres" ] }
tokio = { version = "1.14.0", features = ["full"] }
log = "0.4.14"
log4rs = "1.0.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3