[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2021"

[dependencies]
actix = "0.12.0"
actix-rt = "2.5.0"
actix-web = "3.3.2"
anyhow = "1.0.51"
chrono = "0.4.19"
futures = "0.3.17"
hyper = { version = "0.14.16", features = ["full"] }
tide = "0.16.0"
async-std = { version = "1.10.0", features = ["attributes", "tokio1"] }
reqwest = { version = "0.11.7", features = ["blocking"] }
rocket = "0.5.0-rc.1"
rusqlite = "0.26.3"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.73"
sqlx = { version = "0.5.9", features = [ "runtime-actix-native-tls" , "postgres" ] }
tokio = { version = "1.15.0", features = ["full"] }
log = "0.4.14"
log4rs = "1.0.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3