[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-rt = "2.8.0"
actix-web = "4.3.1"
anyhow = "1.0.70"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
chrono = "0.4.24"
futures = "0.3.28"
hyper = { version = "0.14.26", features = ["full"] }
log = "0.4.17"
log4rs = "1.2.0"
reqwest = { version = "0.11.16", features = ["blocking"] }
rocket = "0.5.0-rc.3"
rusqlite = "0.29.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
sqlx = { version = "0.6.3", features = [ "runtime-actix-native-tls" , "postgres" ] }
tide = "0.16.0"
tokio = { version = "1.28.0", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3