[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2018"

[dependencies]
hyper = "0.14"
reqwest = { version = "0.11.3", features = ["blocking", "json"] }