[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
futures = "0.3.14"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.5.0", features = ["full"] }
reqwest = { version = "0.11.3", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"