[package]
name = "rust"
version = "0.1.0"
authors = ["objektwerks <objektwerks@runbox.com>"]
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-rt = "2.7.0"
actix-web = "4.2.1"
anyhow = "1.0.64"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
chrono = "0.4.22"
futures = "0.3.24"
hyper = { version = "0.14.20", features = ["full"] }
log = "0.4.17"
log4rs = "1.1.1"
reqwest = { version = "0.11.11", features = ["blocking"] }
rocket = "0.5.0-rc.2"
rusqlite = "0.28.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
sqlx = { version = "0.6.1", features = [ "runtime-actix-native-tls" , "postgres" ] }
tide = "0.16.0"
tokio = { version = "1.21.0", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3